[book]
title = "dotfiles"
authors = [ "Davide Peressoni" ]
description = "My literate dotfiles for Nix"
language = "en"
src = "src"


[output.html]
curly-quotes = true
git-repository-url = "https://gitlab.com/DPDmancul/dotfiles"
git-repository-icon = "fa-gitlab"
edit-url-template = "https://gitlab.com/DPDmancul/dotfiles/blob/nix/{path}"


